# docker-compose.yml
version: '3.8'

services:
  user_registration:
    image: user  # your existing image name
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://sanchayjain:sanchayjain123@db:5432/user_registration
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=sanchayjain
      - POSTGRES_PASSWORD=sanchayjain123
      - POSTGRES_DB=user_registration
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge